project:
  type: website
  execute-dir: file
  output-dir: _site

website:
  title: "site"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

