project:
  type: website
  execute-dir: file
  output-dir: _site

website:
  title: "Introduction to the tidyverse"
  repo-url: https://github.com/rstudio-conf-2022/intro-to-tidyverse
  repo-actions: [edit, source, issue]
  page-navigation: true
  
  navbar:
    logo: "images/rstudio-logo.png"
    favicon: "images/rstudio-logo.png"
    background: light
    left:
      - text: "About"
        file: about.qmd
      - text: "Sessions"
        file: sessions.qmd
      - text: "Pre-work"
        file: prework.qmd
    right:
      - icon: github
        aria-label: intro-to-tidyverse on GitHub
        href: https://github.com/rstudio-conf-2022/intro-to-tidyverse
    

format:
  html:
    theme: 
      - cosmo
      - styles.scss

editor: visual

