---
title: "About this experience"
---

RStudio Academy is designed to build skills that you retain long-term: through a combination of interactive lessons, applied project work, group sessions, and check-ins with a mentor -- each of which occurs on a weekly basis -- you will gain comfort with R and its fundamental Tidyverse packages.

## What to expect

Following our kickoff on July 5, we will be spending 6 weeks together as we guide you through the process of learning data science with R. So, what can you expect?

* You will use R to complete a data science project which will serve as the motivating focus for the R content we cover.
* You will learn the core skills you need to complete your project via an online platform with weekly tutorials and practice exercises to explore asynchronously.
* You will attend weekly Office Hours with your mentor and peers, a space to get help or brainstorm ideas for tailoring the project to your own interests.
* Additionally, you will attend weekly Project Sessions facilitated by your mentors where you'll share your milestones with your groupmates and learn from one another.

## Learning objectives

Each week of this course will give you practice with a new set of tools from R and the tidyverse:

1. **R Basics** - Explore the basic components of R, including objects, functions, and packages.
2. **Read and visualize** - Import and visualize data with readr and ggplot2.
3. **Transform tables** - Transform data with dplyr.
4. **Conf in-person practice** - Perform exploratory data analysis with the tools of the tidyverse.
5. **Joins and tidying** - Join datasets and tidy data with dplyr and tidyr.
6. **Model and publish** - Fit a basic model and build polished reports with R Markdown.

## Is this course for me?

**Time commitment:**

This is a 6 week course that runs from July 5 through the week of August 16, and includes two in-person days. This course requires:

* A virtual kickoff event on July 5, 2022 at 12pm EDT
* 3 - 5 hours of asynchronous learning per week
* [Group sessions](sessions.qmd) that meet each week for 1 hour over Zoom
* Two days of in-person learning at rstudio::conf(2022) on July 25-26, 2022

**Consider these questions:**

* You have a dataset of prices of diamonds, as well as their size. Could you make a scatterplot of the two variables using ggplot2?
* You have two datasets, one with information on music genres and age ranges, the other with genres and radio station call names. Can you imagine how you would join them together with a dplyr verb?
* We want to model the wages of people in the United States, using their height and education as predictors. Then, we would like to plot model predictions for each level of educational attainment. Can you imagine how to do this in R?

If you answered "no" to any/all of those questions... great! This Academy experience is for you. By the end of the 6 weeks, you should be able to accomplish all those tasks. If you answered "yes" to all three questions, you may want to consider taking a different workshop.
